[features]
seeds = false
[programs.localnet]
calc = "6xeibRi946XGCVNfRrvz8ovEQtRSnWXhckG4jGFW37aA"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/talhajaami/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
